name: Build and push the Docker image

on:
  release:
    types: [created]
  workflow_run:
    workflows: ["Create GitHub Release"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get release tag
        id: check-tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "tag=${{ github.event.workflow_run.head_commit.message }}" | awk '/^Release v[0-9]+\.[0-9]+\.[0-9]+$/ {print $2}' >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        if: steps.check-tag.outputs.tag != ''
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.check-tag.outputs.tag != ''
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: steps.check-tag.outputs.tag != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.check-tag.outputs.tag != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.check-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
