name: Compile Typescript

on:
  push:
  pull_request:

jobs:
  compile-typescript:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Node dependencies
        run: npm install --save-dev

      - name: Check eslint
        run: npm run eslint

      - name: Compile Typescript
        run: npm run build

      # - name: Run Jest
      #   run: npm run test

